version: '3.8'

services:
  sfd-tracker:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:80"
    container_name: sfd-delivery-tracker
    restart: unless-stopped
    environment:
      - NODE_ENV=production
