services:
  app:
    build: .
    container_name: sfdcompanion
    ports:
      - "5173:5173"
    volumes:
      - .:/app
    environment:
      - NODE_ENV=development
      - CHOKIDAR_USEPOLLING=true
    working_dir: /app
    command: sh -c "npm install && npm run dev -- --host 0.0.0.0"